### ISSUE TITLE
heptio/ark renamed to velero

### ISSUE THREAD

**Issue by waldo121** [petermbenjamin/katacoda-scenarios#1]
Concerns heptio-ark scenario
ark was renamed to velero, these two commands(at least) need to be updated :
`kubectl get deployments -l component=_ark_ --namespace=_heptio-ark_` in step 1
`ark backup create nginx-backup --selector app=nginx` in step 2
The latter outputs:
`An error occurred: the server could not find the requested resource (post backups.ark.heptio.com)` and the first command does not find anything because the namespace and the component name has changed.

**Comment by pbnj** [comment]
Certainly. 

It'll be a while before I can update this scenario as I just had a new born. 

I welcome any PRs, in the meantime.
